### ISSUE TITLE
error during setup of miele

### ISSUE THREAD

**Issue by maxandersen** [docbobo/home-assistant-miele#12]
I finally got my credentials; linked the dev keys to my account and I get the following errors: 

```
019-05-30 00:18:19 ERROR (MainThread) [custom_components.miele.miele_at_home] Failed to retrieve devices: 504
2019-05-30 00:18:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1776223152] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1141, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1163, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/configurator/__init__.py", line 221, in async_handle_service_call
    call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/miele/__init__.py", line 79, in miele_configuration_callback
    await async_setup(hass, config)
  File "/config/custom_components/miele/__init__.py", line 130, in async_setup
    hass.data[DOMAIN][DATA_DEVICES] = _to_dict(client.get_devices(lang))
  File "/config/custom_components/miele/__init__.py", line 98, in _to_dict
    for item in items:
TypeError: 'NoneType' object is not iterable
```

**Comment by maxandersen** [comment]
note, after restart I get: 

```
2019-05-30 00:26:25 WARNING (MainThread) [homeassistant.helpers.service] Unable to find services.yaml for the miele integration
```

**Comment by maxandersen** [comment]
and after a 2nd restart I now have my tumble dryer entry loaded....so it works - but seem to require multiple restarts ?
