### ISSUE TITLE
Component suddenly stopped working

### ISSUE THREAD

**Issue by Filhgd** [docbobo/home-assistant-miele#13]
My component was working great until it just stopped working. You can find my error log below. I didn't change any settings.

Using Hass.io 0.96.5 on a RBP 3 model B+

`2019-08-05 18:17:07 ERROR (MainThread) [homeassistant.setup] Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/miele/__init__.py", line 116, in async_setup
    cache_path=cache)
  File "/config/custom_components/miele/miele_at_home.py", line 103, in __init__
    self.refresh_token()
  File "/config/custom_components/miele/miele_at_home.py", line 128, in refresh_token
    refresh_token=self._token['refresh_token'])
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 374, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 415, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 435, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.`

**Comment by schliflo** [comment]
maybe this hast something to do with the newly released first stable version of the API: https://www.miele.com/developer/news.html

> 1 August 2019
> First public release of Miele 3rd Party API. The current version is V1.0.0
> 
> Changes
> 
> modified: Terms of Use (see here).
> added: Download section.
> added: OAuth2 authorization for API documentation.
> added: New actions for device control.
> added: GET request to check which action is supported by the device.

They also sent an email containing the following:

> Dear users of the Miele 3rd Party API,
> 
>  
> 
> Today marks the end of the beta phase of the Miele 3rd Party API. Tomorrow we will officially release version 1.0 of the API. We would like to express our thanks to all participants of the beta phase and also thank you for the feedback we received. Not all wishes and suggestions could be considered directly, but we promise to continuously add changes and improvements and will welcome your feedback and suggestions at any time (included them in our backlog).
> 
>  
> 
> What’s new (changes)?
> 
> First of all we have adapted our Terms of Use, this was necessary to allow commercial users to use the API.
> 
> In addition, we made small adjustments to individual endpoints, for example the spinningSpeed is now localized.
> 
> We have also increased the number of possible actions. Before an action is executed on a device, a GET action can be used to check which actions are available.
> 
>  
> 
> What's next?
> 
> We are going to change the registration process. With this new process, there is no need to request login information via email. Client ID and client secret can be created directly on developer.miele.com.
> However, with this change it is necessary for all API users to create new credentials. The old credentials will expire 30 days after the introduction date of the new registration.
> We will soon inform you about the date of the change by email.
> 
>  
> 
> Thanks again for participating in the beta program.
> 
>  
> 
> Best regards
> 
> Your Miele 3rd Party API Team

Just wanted to leave this here as mine is broken as well, but I didn't have time to look at it yet.

**Comment by Filhgd** [comment]
Any updates?
